# Generated by Django 4.2.2 on 2023-07-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
    ]
