# Generated by Django 4.2.2 on 2023-07-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_role_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_role_in_org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_in_org', to='user.memberuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='user.role')),
            ],
        ),
    ]
